Backport API introduced in openssl 3.5.0
This commit [1] introduced this new API which is used by pem.h from
openssl and it should be provided by asn1.h which is vendored here so
it goes out of sync and causes build errors e.g

In file included from ./os_stub/cryptlib_openssl/pk/x509.c:18:
/usr/include/openssl/pem.h:399:28: error: unknown type name 'OSSL_i2d_of_void_ctx'
  399 | int PEM_ASN1_write_bio_ctx(OSSL_i2d_of_void_ctx *i2d, void *vctx,

[1] https://github.com/openssl/openssl/commit/35f6e7ea02b599d5aaf220b4720cbadd946d8023

Signed-off-by: Khem Raj <raj.khem@gmail.com>